
spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true

server:
  port: 8201

  # eureka连接地址
  # defaultZone 默认地点
  # 其他地点配置，需要由云服务来提供
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:  hystrtix.stream
